### ISSUE TITLE
postRemote work normally in adapter but work like postlocal in mobile activity

### ISSUE THREAD

**Issue by letroll** [tajchert/BusWear#8] opened 2015-05-24 18:48 UTC
I have the bug in the title, can you help me?

**Comment by tajchert** [comment] 2015-05-24 21:20
What adapter do you mean? Can you paste some code that doesn't work for you - or even a sample project?

**Comment by letroll** [comment] 2015-05-25 10:44
Sorry I do not have this code for now, but basically in the code of a onEvent, I was doing a Eventbus.getDefault.postRemote and it was acting like a postLocal

**Comment by tajchert** [comment] 2015-05-26 23:02
As sample project uses it and it works fine I'm closing this due to lack of being able to reproduce. If you find that bug able to reproduce please create new project or just form sample one and make it so it reproduces a bug or shows a incorrect way of sending data.

**Closed as completed by tajchert** 2015-05-26 23:02 UTC
